---
- hosts: ubuntu
  become: true

  tasks:
  - name: update repository index
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: rhel
  become: true

  tasks:
  - name: update repository
    yum:
      update_cache: true

  - name: install Apache2 
    yum:
      state: latest
      name: httpd

  - name: Enable httpd Service
    systemd:
      state: started
      name: httpd
      enabled: yes

