---
- hosts: ubuntu
  pre_tasks:

  - name: Install Apache2 and PHP
    tags: apache,ubuntu,debian
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: rhel
  pre_tasks:

  - name: Install httpd and PHP
    tags: rhel,suse
    yum:
      name:
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["RedHat"]
